### ISSUE TITLE
3.0.6 crashes as soon as I choose a file

### ISSUE THREAD

**Issue by Adrien2002** [xperia64/timidity-ae#17]
Hi,

I've been a fidel timidity-ae user for more than a decade, having no issue at all until that very new version from october 1st.

The app is working perfectly UNTIL I try to play any audio file. MID, OGG, MP3 etc… The app will just close itself without error message.

My phone is a Google Pixel 8a.

What can I share to help you identify the cause? Are there any logs somewhere?

**Comment by TacoTheDank** [comment]
@Adrien2002 Here's a version of 3.0.5 I had saved from 2019. I'm pretty sure it's from Google Play (when the app was still on there). You could use this for the time being.

[TimidityAE_v3.0.5(95).zip](https://github.com/user-attachments/files/17267814/TimidityAE_v3.0.5.95.zip)

**Comment by TacoTheDank** [comment]
I captured the crash from the 3.0.6 F-Droid version:
```
FATAL EXCEPTION: main
Process: com.xperia64.timidityae, PID: 25932
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.xperia64.timidityae.MusicService_RECEIVER flg=0x10 (has extras) } in com.xperia64.timidityae.MusicService$2@d2a9c49
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1658)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=25932, uid=10117 requires android.permission.FOREGROUND_SERVICE
	at android.os.Parcel.createException(Parcel.java:2088)
	at android.os.Parcel.readException(Parcel.java:2056)
	at android.os.Parcel.readException(Parcel.java:2004)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7152)
	at android.app.Service.startForeground(Service.java:707)
	at com.xperia64.timidityae.MusicService.updateNotification(MusicService.java:1161)
	at com.xperia64.timidityae.MusicService.play(MusicService.java:896)
	at com.xperia64.timidityae.MusicService$2.onReceive(MusicService.java:256)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1648)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:7603)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1425)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1076)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:16894)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3287)
```

**Comment by forgettablepyromaniac** [comment]
Can confirm this is happening to my phone as well. Galaxy S20, Android version 13. Downgraded by uninstalling and then installing the previous version on F-Droid.

Still a great piece of software, but damn. :/

**Comment by mikadataanalyst** [comment]
Yep, had the same on my Xiaomi MI 8 Lite using the F-Droid version. Reading and playing do start though, but it crashes real soon. Playing does go on after crash and error message shows. 

Android version 10

Too bad, had just discovered and sounded real nice :-)
 
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.xperia64.timidityae.MusicService_RECEIVER flg=0x10 (has extras) } in com.xperia64.timidityae.MusicService$2@eeb56be
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1566)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=21930, uid=10441 requires android.permission.FOREGROUND_SERVICE
	at android.os.Parcel.createException(Parcel.java:2074)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.os.Parcel.readException(Parcel.java:1990)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6303)
	at android.app.Service.startForeground(Service.java:707)
	at com.xperia64.timidityae.MusicService.updateNotification(MusicService.java:1161)
	at com.xperia64.timidityae.MusicService.play(MusicService.java:896)
	at com.xperia64.timidityae.MusicService$2.onReceive(MusicService.java:256)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1556)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:6146)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1324)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:973)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:14311)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2855)
```

**Comment by BigErn77** [comment]
Same problem here on Moto G Power 2021. As soon as I select a midi, the app crashes.

**Comment by farvardin** [comment]
I can confirm the 3.0.5 version is working fine, while the 3.0.6 is crashing when loading a midi file on my Poco F3 running lineageos. The 3.0.5 version should be distributed on f-droid along with the 3.0.6.

**Comment by seacat17** [comment]
Still borked...
